# Generated by Django 4.0.6 on 2022-07-21 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_remove_articles_category_remove_articles_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='pwd',
        ),
    ]
