# Generated by Django 4.0.6 on 2022-07-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_remove_articles_pwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='source',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='来源'),
        ),
    ]
