# Generated by Django 4.0.6 on 2022-07-06 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userinfo_height_userinfo_score_userinfo_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='height',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='score',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='weight',
        ),
    ]
