# Generated by Django 4.0.6 on 2022-07-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('content', models.TextField(verbose_name='反馈信息')),
                ('status', models.BooleanField(default=False, verbose_name='是否处理')),
                ('processing_content', models.TextField(blank=True, null=True, verbose_name='回复的内容')),
            ],
            options={
                'verbose_name_plural': '用户反馈',
            },
        ),
    ]
