# Generated by Django 4.0.6 on 2022-07-06 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
