# Generated by Django 4.0.6 on 2022-07-06 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('digg_count', models.IntegerField(default=0, verbose_name='点赞')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('comment_count', models.IntegerField(default=0, verbose_name='子评论数')),
                ('drawing', models.TextField(blank=True, null=True, verbose_name='配图')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.articles', verbose_name='评论文章')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.comment', verbose_name='是否是父评论')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
            ],
            options={
                'verbose_name_plural': '评论',
            },
        ),
    ]
